### PR TITLE
Import CSV from moneywallet

### LINKED ISSUE #395: Import CSV from MoneyWallet (com.oriondev.moneywallet)
**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**

- [ ] Yes
- [x] No
- [ ] Kinda (please describe):

### Google PlayStore URL to the app from which you want to import:
- URL: https://play.google.com/store/apps/details?id=com.oriondev.moneywallet&hl=en_IN&gl=US

### Attach Samples CSV from the app:

Attach an exported CSV file from the app to this issue.

**CSV file requirements:**
- [ ] includes Income type transaction
- [ ] includes Expense type transaction
- [ ] includes Transfer type transaction (optional)
- [ ] includes title, description, all attributes available in the app (optional)

**Is CSV export from the app free?**

- [x ] Yes
- [ ] No
- [ ] It depends (please describe):

_Put an `x` in the boxes that apply._

- [x] Demo: Checking checkbox using `[x]`

## Developer/Contributor Notes

- Checkout
  this **[Sample Commit](https://github.com/ILIYANGERMANOV/ivy-wallet/commit/323ed68343a0904ee33f226480716a30368fd646)**
  to see how import CSV works in Ivy Wallet
- Make sure that the imported dates of the transactions are correct

### PR DESCRIPTION
**Pull request by Holi0317**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `develop` branch.
- [x] I understand the **[Ivy Developer Guidelines](../docs/Developer-Guidelines.md)**.
- [x] I've read the **[Contribution Guidelines](https://github.com/ILIYANGERMANOV/ivy-wallet/blob/main/CONTRIBUTING.md)**.
- [ ] The code builds and is tested on an actual Android device.
- [x] I confirm that I've run the code locally and everything works as expected.
- [ ] I confirm that I've run Ivy Wallet's UI tests (`androidTest`) and all tests are passing
  successfully.
  - It broke on "AddLoanRecord" on latest develop before my commit

_Important: Don't worry if you experience flaky UI tests. Just re-run the failed ones again and if they pass => it's all good!_

_Put an `x` in the boxes that apply._
- [x] Demo: Checking checkbox using `[x]`

## Pull Request Type
Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, new lines, etc.)
- [ ] Refactoring (no functional changes, renaming)
- [ ] Small improvement (fix typo, UI fine-tune, change color or something small)
- [ ] Gradle Build related changes
- [ ] Dependencies update (updating libraries)
- [ ] Documentation (clarifying comments, KDoc)
- [ ] Tests (Unit, Integration, UI tests)
- [ ] Other (please describe):

_Put an `x` in the boxes that apply._

## Does this PR closes any GitHub Issues?
Check **[Ivy Wallet Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)**.
- Closes #395

## What's changed?
Describe with a few bullets **what's new:**

- Add support on importing csv from moneywallet

## How to run Ivy Wallet's UI tests (`androidTest`)
**Connect Android Emulator**
- Pixel 5 API 29+ AVD emulator _(recommended)_
- Pixel 3XL API 29+ AVD emulator _(recommended)_
- Large screen physical device _(might also work)_

**Method 1: Android Studio UI**
- Find `com (androidTest)` package
- Right click
- `Run 'Tests in 'com''`

_Note: If you've checked "Compact Middle Packages" the option will appear as `com.ivy.wallet (androidTest)`._

**Method 2: Gradle Wrapper**
- `chmod +x gradlew` (Linux)
- `./gradlew connectedDebugAndroidTest`

**Method 3: Fastlane**
- Install Ruby 2.7
- `bundle install`
- `bundle exec fastlane ui_tests`

### CODE REVIEW

**Comment by ILIYANGERMANOV** [comment]
Nice!! There's just one conflict in `strings.xml`. Can you resolve it and I'll merge it?

**Comment by Holi0317** [comment]
Resolved the merge conflict

**Comment by Vishwa-Raghavendra** [comment]
The merge conflict resolution by @Holi0317 might lead to the app breaking down as some strings were removed from strings.xml

so when the app is loaded in English(default) it might crash

@ILIYANGERMANOV 
do add the following lines to strings.xml 


<string name="parent_category">Parent Category</string>
<string name="marked_parent_category">*This is marked as a Parent Category</string>
<string name="unpack_all_subcategories">Unpack All Subcategories</string>

**Comment by ILIYANGERMANOV** [comment]
Thank you @Vishwa-Raghavendra!

**Comment by Vishwa-Raghavendra** [comment]
@ILIYANGERMANOV No problem,
I have updated the comment so that you can directly copy the missing strings,

previously markdown was processing it and it resulted in clearing the tags :p

**Comment by ILIYANGERMANOV** [comment]
@Vishwa-Raghavendra can you submit a PR for it, I'm really focused into `modularization` and will forget about it

**Comment by Vishwa-Raghavendra** [comment]
Sure, No Problem

**Pull request merged**
