### PR TITLE
Added CustomExchangeRate

### LINKED ISSUE #582: Set custom exchange rate on account transfer function
**What do you want to be added or improved?**
As a user, I want to set a custom exchange rate on transfer multi-currency  (ex: us dollar to euro)

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [ ] I'm not sure but I've checked.

**Explain with bullets why do you need it**
- Actually, in my country, the best way to exchange money is with another person and it usually doesn't follow the official exchange rate
- When I do this on the app with the transfer function, it shows an inexact amount on the wallet
- The way I handle it is to add an "expense" and then an "income" but this way make statistics confusing

**Explain how do you imagine it in detail**
I Imagine an input field on the "add account transfer screen" where I can set my custom exchange rate of the transfer
**I'd like to:**
- input field where I can set my custom exchange rate of the transfer

### PR DESCRIPTION
**Pull request by Vishwa-Raghavendra**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `develop` branch.
- [x] I've read the **[Contribution Guidelines](https://github.com/ILIYANGERMANOV/ivy-wallet/blob/main/CONTRIBUTING.md)**.
- [x] The code builds and is tested on an actual Android device.
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] I confirm that I've run Ivy Wallet's UI tests (`androidTest`) and all tests are passing
  successfully.

_Important: Don't worry if you experience flaky UI tests. Just re-run the failed ones again and if they pass => it's all good!_

_Put an `x` in the boxes that apply._
- [x] Demo: Checking checkbox using `[x]`

## Pull Request Type
Please check the type of change your PR introduces:
Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, new lines, etc.)
- [ ] Refactoring (no functional changes, renaming)
- [ ] Small improvement (fix typo, UI fine-tune, change color or something small)
- [ ] Gradle Build related changes
- [ ] Dependencies update (updating libraries)
- [ ] Documentation (clarifying comments, KDoc)
- [ ] Tests (Unit, Integration, UI tests)
- [ ] Other (please describe):

_Put an `x` in the boxes that apply._

## Does this PR closes any GitHub Issues?
Check **[Ivy Wallet Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)**.
- Closes #582 

## What's changed?
Describe with a few bullets **what's new:**
- a Ability to set custom Exchange rate and now exchanged rate is displayed in transaction cards
- b Custom Exchange Rate is can be set only up to 4 decimal points 

Pic 1
[---]
Pic 2

## How to run Ivy Wallet's UI tests (`androidTest`)
**Connect Android Emulator**
- Pixel 5 API 29+ AVD emulator _(recommended)_
- Pixel 3XL API 29+ AVD emulator _(recommended)_
- Large screen physical device _(might also work)_

**Method 1: Android Studio UI**
- Find `com (androidTest)` package
- Right click
- `Run 'Tests in 'com''`

_Note: If you've checked "Compact Middle Packages" the option will appear as `com.ivy.wallet (androidTest)`._

**Method 2: Gradle Wrapper**
- `chmod +x gradlew` (Linux)
- `./gradlew connectedDebugAndroidTest`

**Method 3: Fastlane**
- Install Ruby 2.7
- `bundle install`
- `bundle exec fastlane ui_tests`

### CODE REVIEW

**Comment by ILIYANGERMANOV** [comment]
That's a very cool feature @Vishwa-Raghavendra! Thank you  :)

I'm planning to make a release in the upcoming days, a lot of new features are in the app which our users and community would like!

**Comment by Pkcarreno** [comment]
Very good feature, I already had the opportunity to try it, in my case it does not let me edit the amount

Pressing the numbers does not change the exchange rate, I wish I could help you more but I don't know kotlin

**Comment by Vishwa-Raghavendra** [comment]
Hi @Pkcarreno,
Thanks a lot for the bug Report :) 

This is fixed in #687

**Comment by Pkcarreno** [comment]
amazing, thank you very much

**Pull request merged**
