### PR TITLE
add russian translation

### LINKED ISSUE #802: [TRANSLATION] Russian
**What do you want to be added or improved?**
Add Rus localization.

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [ ] I'm not sure but I've checked.

**Explain with bullets why do you need it**
- By starting using the app all categories in English
- User experience

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
- I can suggest for you use Weblate for kv translating

### PR DESCRIPTION
**Pull request by llama-0**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `develop` branch.
- [x] I understand the **[Ivy Developer Guidelines](../docs/Developer-Guidelines.md)**.
- [x] I've read the **[Contribution Guidelines](https://github.com/ILIYANGERMANOV/ivy-wallet/blob/main/CONTRIBUTING.md)**.
- [x] The code builds and is tested on an actual Android device.
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] I confirm that I've run Ivy Wallet's UI tests (`androidTest`) and all tests are passing
  successfully.

## Pull Request Type
Please check the type of change your PR introduces:

- [x] Other: translation

## Does this PR closes any GitHub Issues?
- Closes #802 

## What's changed?
- added values-ru/strings.xml file

## Additional information
In some places in the app translation is not truly correct due to [this issue](https://github.com/ILIYANGERMANOV/ivy-wallet/issues/855) I raised earlier. I'll take this issue next or leave it for someone else who's also interested.

### CODE REVIEW

**Comment by ILIYANGERMANOV** [comment]
Hi @llama-0, thank you for your PR! I guess there are missing translation or other errors because "lint" check is failing. Can you have a look?

**Comment by StarHamster** [comment]
I'll work on it and fix it

**Comment by ILIYANGERMANOV** [comment]
@StarHamster the error:

23:21:21]: ▸ /home/runner/work/ivy-wallet/ivy-wallet/app/src/main/res/values-ru/strings.xml:65: Error: Inconsistent formatting types for argument #1 in format string transactions_imported ('%1$s'): Found both 's' here and 'd' in values/strings.xml [StringFormatMatches]
[23:21:21]: ▸ <string name="transactions_imported">%1$s транзакций</string>
[23:21:21]: ▸ ~~~~
[23:21:21]: ▸ /home/runner/work/ivy-wallet/ivy-wallet/app/src/main/res/values/strings.xml:65: Conflicting argument type (`d') here

**Comment by StarHamster** [comment]
Yeah, I saw, thx @ILIYANGERMANOV . There're many other mistakes. I'll add fix commit tommorow 💤

**Comment by llama-0** [comment]
Hi! I'm sorry I've missed so many things 😱Thank you for all the corrections! This is my first ever contribution to opensource, I'm extremely nervous, but I hope I'll do better in the future.

**Comment by ILIYANGERMANOV** [comment]
No worries, @llama-0! We appreciate your contribution and would be happy to see more in future 🚀

**Pull request merged**
