### PR TITLE
RecyclerView Library Update

### PR DESCRIPTION
**Pull request by Vishwa-Raghavendra**
## Pull Request (PR) Checklist

Please check if your pull request fulfills the following requirements:

- [x] The PR is submitted to the `develop` branch.
- [x] I've read the **[Contribution Guidelines](https://github.com/ILIYANGERMANOV/ivy-wallet/blob/main/CONTRIBUTING.md)**.
- [x] The code builds and is tested on an actual Android device.
- [x] I confirm that I've run the code locally and everything works as expected.

_Put an `x` in the boxes that apply._

- [x] Demo: Checking checkbox using `[x]`

## Pull Request Type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [x] Small update (fix typo, change color or something)
- [ ] Gradle Build related changes
- [x] Dependencies update (updating libraries)
- [ ] Documentation
- [ ] Other (please describe):

_Put an `x` in the boxes that apply._

## Does this PR closes any GitHub Issues?

Check **[Ivy Wallet Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)**.

- Closes #N/A (type issue number here)

## What's changed?
- Updated RecyclerView Library from 1.2.0 -> 1.2.1

_This PR template style was inspired by [ionic-framework](https://github.com/ionic-team/ionic-framework/blob/main/.github/PULL_REQUEST_TEMPLATE.md)._

### CODE REVIEW

**Comment by ILIYANGERMANOV** [comment]
Hi @Vishwa-Raghavendra, thanks for adding the PR. I can see now your commit on `develop`, however, there is something weird with you profile. Only yours from all contributors isn't clickable => maybe because of that GitHub doesn't show you in the contributors graph?

Can you check your Github account settings?

## Solution 1
"If the email address used for the commit is not connected to your account on GitHub.com, you must add the email address to your account on GitHub.com. ... If you use such an email for your commits, the commits will not be linked to your GitHub profile and will not show up in your contribution graph."

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile

Please make sure to fix that, I really want your name to be displayed as contributor :)

**Comment by Vishwa-Raghavendra** [comment]
Hi ILIYANGERMANOV,

Thanks a ton for pointing that out :)
It was indeed an Email-Mismatch error, it has been resolved now i have
linked the email address to my profile.

Thanks again for pointing it out :)

**Comment by ILIYANGERMANOV** [comment]
Perfect @Vishwa-Raghavendra! Now I can see that your profile is linked to the commit. I think that 24h after I merge your second PR on `main` you should be visible as a contributor. If not you'll to submit another PR with a commit where the email mismatch is fixed.

**Comment by Vishwa-Raghavendra** [comment]
Awesome, thanks! 😀

**Pull request merged**
