### PR TITLE
Added Swipe to Change Month in ItemStatisticScreen

### LINKED ISSUE #148: Change months in ItemStatistic screen with horizontal swipe
**What do you want to be added or improved?**
As a user I want to change months in ItemStatisticScreen.kt with left and right swipe.

Screenshot_20211117-175343_Ivy Wallet

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [ ] I'm not sure but I've checked.

_Put an `x` in the boxes that apply._

- [x] Demo: Checking checkbox using `[x]`

**Explain with bullets why do you need it**
- convenience
- feels intuitive

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
**I'd like to:**
- swipe left => next month
- swipe right => previous month

Tips:
- re-use prev/next month logic from the screen
- re-use horizaontalSwipeListener()

### PR DESCRIPTION
**Pull request by Vishwa-Raghavendra**
## Pull Request (PR) Checklist

Please check if your pull request fulfills the following requirements:

- [x] The PR is submitted to the `develop` branch.
- [x] I've read the **[Contribution Guidelines](https://github.com/ILIYANGERMANOV/ivy-wallet/blob/main/CONTRIBUTING.md)**.
- [x] The code builds and is tested on an actual Android device.
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] I confirm that I've run Ivy Wallet's UI tests (`androidTest`) and all tests are passing
  successfully.

_Important: Don't worry if you experience flaky UI tests. Just re-run the failed ones again and if they pass => it's all good!_

_Put an `x` in the boxes that apply._

- [x] Demo: Checking checkbox using `[x]`

### How to run Ivy Wallet's UI tests (`androidTest`)

**Connect Android Emulator**
- Pixel 5 API 29+ AVD emulator _(recommended)_
- Pixel 3XL API 29+ AVD emulator _(recommended)_
- Large screen physical device _(might also work)_

**Method 1: Android Studio UI**
- Find `com (androidTest)` package
- Right click
- `Run 'Tests in 'com''`

_Note: If you've checked "Compact Middle Packages" the option will appear as `com.ivy.wallet (androidTest)`._

**Method 2: Gradle Wrapper**
- `chmod +x gradlew` (Linux)
- `./gradlew connectedDebugAndroidTest`

**Method 3: Fastlane**
- Install Ruby 2.7
- `bundle install`
- `bundle exec fastlane ui_tests`

## Pull Request Type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [x] Small update (fix typo, UI fine-tune, change color or something small)
- [ ] Gradle Build related changes
- [ ] Dependencies update (updating libraries)
- [ ] Documentation
- [ ] Tests (Unit, Integration, UI tests)
- [ ] Other (please describe):

_Put an `x` in the boxes that apply._

## Does this PR closes any GitHub Issues?

Check **[Ivy Wallet Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)**.

- Closes #148

## What's changed?

Describe with a few bullets **what's new:**
- Ability to change months via horizontal change in ItemStatisticScreen
-
-

_This PR template style was inspired by [ionic-framework](https://github.com/ionic-team/ionic-framework/blob/main/.github/PULL_REQUEST_TEMPLATE.md)._

### CODE REVIEW

**Review by ILIYANGERMANOV — CHANGES_REQUESTED** [review]
Hi, thanks for the PR! Your solution is good just apply the Ivy Wallet code style.

Changes:
- add names to function parameters
- see how I use Modifier#horizontalSwipe()

**Comment by Vishwa-Raghavendra** [comment]
I have updated the code according to Ivy Wallet code Style

**Review by ILIYANGERMANOV — CHANGES_REQUESTED** [review]
Thansk for updating! The code style is good now :)
One more thing - SWIPE_HORIZONTAL_THRESHOLD must not be Constants because this specific threshold is local only for the ItemStatisticScreen. 

Just use `sensitivity = 150` (w/o constant)
150 so the gesture is more sensitive

**Comment by Vishwa-Raghavendra** [comment]
Code Updated :)

**Review by ILIYANGERMANOV — APPROVED** [review]
Thanks for the quick response, man! It's perfect now. I'm merging it!

For your next PRs please add "Closes #148; <your message>" in any of the commits so you can take the full credit for closing the issue :)

**Comment by ILIYANGERMANOV** [comment]
@Vishwa-Raghavendra ups, there's one problem! You submit the PR to `main`. Change the PR to `develop` and I'll merge it right away with the latest version of the code.

**Pull request closed without merging**
