### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jevo160296**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `develop` branch.
- [x] I understand the **[Ivy Developer Guidelines](../docs/Developer-Guidelines.md)**.
- [x] I've read the **[Contribution Guidelines](https://github.com/ILIYANGERMANOV/ivy-wallet/blob/main/CONTRIBUTING.md)**.
- [x] The code builds and is tested on an actual Android device.
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] I confirm that I've run Ivy Wallet's UI tests (`androidTest`) and all tests are passing
  successfully.

_Important: Don't worry if you experience flaky UI tests. Just re-run the failed ones again and if they pass => it's all good!_

_Put an `x` in the boxes that apply._
- [x] Demo: Checking checkbox using `[x]`

## Pull Request Type
Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, new lines, etc.)
- [ ] Refactoring (no functional changes, renaming)
- [ ] Small improvement (fix typo, UI fine-tune, change color or something small)
- [ ] Gradle Build related changes
- [ ] Dependencies update (updating libraries)
- [ ] Documentation (clarifying comments, KDoc)
- [x] Tests (Unit, Integration, UI tests)
- [ ] Other (please describe):

_Put an `x` in the boxes that apply._

## What's changed?
Describe with a few bullets **what's new:**
- Button skip and skip all on the account detail fixed.
- Added unit tests for pay and skip planned payments on the homescreen and the account detail screen

## How to run Ivy Wallet's UI tests (`androidTest`)
**Connect Android Emulator**
- Pixel 5 API 29+ AVD emulator _(recommended)_
- Pixel 3XL API 29+ AVD emulator _(recommended)_
- Large screen physical device _(might also work)_

**Method 1: Android Studio UI**
- Find `com (androidTest)` package
- Right click
- `Run 'Tests in 'com''`

_Note: If you've checked "Compact Middle Packages" the option will appear as `com.ivy.wallet (androidTest)`._

**Method 2: Gradle Wrapper**
- `chmod +x gradlew` (Linux)
- `./gradlew connectedDebugAndroidTest`

**Method 3: Fastlane**
- Install Ruby 2.7
- `bundle install`
- `bundle exec fastlane ui_tests`

### CODE REVIEW

**Comment by ILIYANGERMANOV** [comment]
That's awesome @jevo160296! I've made a major refactoring in our UI tests - can you fetch, accept my changes and re-write the tests that you've added. I bet that you'll like the new way for writing tests 👌 (which we'll improve even more)

Thank you for adding tests - let's make Ivy Wallet the most stable project!

**Comment by jevo160296** [comment]
Hi @ILIYANGERMANOV please don't merge this pull request yet, I'm cheking if the tests are still working good

**Comment by ILIYANGERMANOV** [comment]
Sure thing! Please rewrite your tests by chaining the methods with "." dot.

Example:

quickOnboarding()
  .clickAddFAB()
  .addPlannedPayment()
  ...


You'll see only the appropriate methods and available UI as a suggestion after you write "." Does that make sense?

**Comment by jevo160296** [comment]
Yes thanks, I finished it, I'm running all the tests. I'll upload the changes in a few minutes.

**Comment by jevo160296** [comment]
@ILIYANGERMANOV done, all tests passed. It's easier to build test now!.

**Comment by ILIYANGERMANOV** [comment]
Looks good @jevo160296! Thank you 👍 I'll improve the way we write tests even further but that's a decent starting point - great PR!

**Pull request merged**
