### PR TITLE
Create Spanish translation

### LINKED ISSUE #179: [TRANSLATION] Spanish

### PR DESCRIPTION
**Pull request by Pkcarreno**
## Pull Request (PR) Checklist

- [x] The PR is submitted to the `develop` branch.
- [x] I've read the **[Contribution Guidelines](https://github.com/ILIYANGERMANOV/ivy-wallet/blob/main/CONTRIBUTING.md)**.

## Pull Request Type

- [x] Other: translation

## Does this PR closes any GitHub Issues?

- Closes #179

## What's changed?

- Added Spanish translation.

### CODE REVIEW

**Comment by Pkcarreno** [comment]
I don't quite understand this lint-release error

**Comment by ILIYANGERMANOV** [comment]
@Pkcarreno I guess there's untranslated string is Spanish. I'll check the log and give you more info :)

**Comment by Pkcarreno** [comment]
@ILIYANGERMANOV wow, I'm going to check again, but there are several strings that are the same in Spanish as in English, at this moment I only remember `Ivy telegram` because in Spanish it sounds correct

**Comment by ILIYANGERMANOV** [comment]
Screenshot_20220507-222628_Chrome
@Pkcarreno

**Comment by Pkcarreno** [comment]
@ILIYANGERMANOV ok, i got it, when i forked i didn't have those lines. I'm already making the changes

**Pull request merged**
