### PR TITLE
Fixed Issue #602:Add auto dark theme

### LINKED ISSUE #602: Dark Mode Automatically
According to the phone system, many apps turn in to dark mode. Maybe a check for activate this function besides manually option?

### PR DESCRIPTION
**Pull request by MohitMandalia**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `develop` branch.
- [x] I've read the **[Contribution Guidelines](https://github.com/ILIYANGERMANOV/ivy-wallet/blob/main/CONTRIBUTING.md)**.
- [x] The code builds and is tested on an actual Android device.
- [x] I confirm that I've run the code locally and everything works as expected.
- [ ] I confirm that I've run Ivy Wallet's UI tests (`androidTest`) and all tests are passing
  successfully.

_Important: Don't worry if you experience flaky UI tests. Just re-run the failed ones again and if they pass => it's all good!_

_Put an `x` in the boxes that apply._
- [x] Demo: Checking checkbox using `[x]`

## Pull Request Type
Please check the type of change your PR introduces:
Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, new lines, etc.)
- [ ] Refactoring (no functional changes, renaming)
- [ ] Small improvement (fix typo, UI fine-tune, change color or something small)
- [ ] Gradle Build related changes
- [ ] Dependencies update (updating libraries)
- [ ] Documentation (clarifying comments, KDoc)
- [ ] Tests (Unit, Integration, UI tests)
- [ ] Other (please describe):

_Put an `x` in the boxes that apply._

## Does this PR closes any GitHub Issues?
Check **[Ivy Wallet Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)**.
- Closes #602 (type issue number here)

## What's changed?
Describe with a few bullets **what's new:**
- Added an Auto mode for changing the theme automatically as per default device theme.

## How to run Ivy Wallet's UI tests (`androidTest`)
**Connect Android Emulator**
- Pixel 5 API 29+ AVD emulator _(recommended)_
- Pixel 3XL API 29+ AVD emulator _(recommended)_
- Large screen physical device _(might also work)_

**Method 1: Android Studio UI**
- Find `com (androidTest)` package
- Right click
- `Run 'Tests in 'com''`

_Note: If you've checked "Compact Middle Packages" the option will appear as `com.ivy.wallet (androidTest)`._

**Method 2: Gradle Wrapper**
- `chmod +x gradlew` (Linux)
- `./gradlew connectedDebugAndroidTest`

**Method 3: Fastlane**
- Install Ruby 2.7
- `bundle install`
- `bundle exec fastlane ui_tests`

### CODE REVIEW

**Comment by MohitMandalia** [comment]
Have run the test cases all are passing except 6 of the LoansTest which doesn't pass in current develop branch too atleast for my devices they show that Error due to compose being busy.

**Review by ILIYANGERMANOV — APPROVED** [review]

**Comment by ILIYANGERMANOV** [comment]
@MohitMandalia feel free to have a look at it :) I'd appreciate it!

**Comment by MohitMandalia** [comment]
I am talking about this PR like it shows that this failed somehow when you merged

**Comment by ILIYANGERMANOV** [comment]
Actually, it's in `main`. Then it's all good!
https://github.com/ILIYANGERMANOV/ivy-wallet/commit/9b23125803c87b6f54063216aca37df80f728518

The lint check may be failing because it's executed on release build type or idk? (haven't investigated) However, I can confirm that your implementation is tested and works!

**Comment by MohitMandalia** [comment]
> @MohitMandalia that's awesome! Tbh, you know the issues better than me xD Last days I didn't have much time for the project.
> 
> Feel free to pick any issue that you find interesting or want to work on. Also, if you have ideas for improving the app and make it better you're more to encouraged to develop them :)
> 
> It's a community-driven and open-source project, and you're the ones to decide its future!

Cool man that's really good to hear. Would surely check something out and if I get some good idea for improvements would surely work on the same.

**Comment by ILIYANGERMANOV** [comment]
Hi @MohitMandalia if you're interested, you can have a look at #34 so we can implement attachments and automatic backups. That would be a killer feature and a great leap for our project!

**Comment by MohitMandalia** [comment]
> Hi @MohitMandalia if you're interested, you can have a look at #34 so we can implement attachments and automatic backups. That would be a killer feature and a great leap for our project!

Definitely would love to help I'll check on it and see what can be done.

**Pull request merged**
